---
version: '3'
services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - app:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matamo.rule=${TRAEFIK_HOSTS}"
      - "traefik.http.routers.matamo.entrypoints=websecure"
      - "traefik.http.routers.matamo.tls.certresolver=letsencrypt"
      - "traefik.http.services.matamo.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"        
    networks:
      - proxy
      - app
  app:
    image: matomo:fpm-alpine
    restart: always
    networks:
      - db
      - app
    volumes:
      - app:/var/www/html
    tmpfs:
      - /var/www/html/tmp:uid=82,gid=82
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: piwik_
      MATOMO_DATABASE_USERNAME: ${MYSQL_USER}
      MATOMO_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MYSQL_DATABASE}
    depends_on:
      - db
  cron:
    image: matomo:fpm-alpine
    restart: always
    networks:
      - db
    volumes:
      - app:/var/www/html:ro
    tmpfs:
      - /var/www/html/tmp:uid=82,gid=82
    depends_on: [app]
    entrypoint: "sh -c 'while true; do php console core:archive --url=https://piwik.rule88.nl/; sleep 600; done'"
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    labels:
    labels:
      mysql.backup: true
    volumes:
      - db:/var/lib/mysql
      - db-backup:/backup
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - db
volumes:
  db:
  db-backup:
    labels:
      backup: true
  app:
    labels:
      backup: true
networks:
  app:
  db:
  proxy:
    external: true
